In [4]:
import numpy as np
import array

In [5]:
arr1 = array.array('i',[i for i in range(10)])
print(arr1)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [6]:
print(arr1[5])

5


In [7]:
arr2 = np.array([i for i in range(10)])
print(arr2)
print(arr2[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [8]:
arr2[5]=100
print(arr2)

[  0   1   2   3   4 100   6   7   8   9]


In [9]:
arr2[5] = 3.14
print(arr2)
print(arr2.dtype)

[0 1 2 3 4 3 6 7 8 9]
int64


In [10]:
arr3 = np.array([3.14, 2.2, 4, 4])
print(arr3.dtype)

float64


In [ ]:
arr4 = np.zeros(10)