In [1]:
import numpy as np
import array

In [2]:
arr1 = array.array('i',[i for i in range(10)])
print(arr1)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
print(arr1[5])

5


In [4]:
arr1[5] = 100

In [5]:
print(arr1)

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])


In [6]:
arr2 = np.array([i for i in range(10)])

In [7]:
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [1]:
print(arr2[5])

NameError: name 'arr2' is not defined

In [9]:
print(arr2.dtype)

int32


In [ ]:
arr5 = np.zeros(10, float)
print(arr5)

In [14]:
arr6 = np.zeros((3,5))
print(arr6)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
arr7 = np.ones(10)
print(arr7)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [17]:
arr9 = np.full(10, 666)
print(arr9)

[666 666 666 666 666 666 666 666 666 666]


In [18]:
arr11 = np.full((3,5),888,float)
print(arr11)


[[888. 888. 888. 888. 888.]
 [888. 888. 888. 888. 888.]
 [888. 888. 888. 888. 888.]]


In [19]:
print(arr11.dtype)

float64


In [21]:
arr12 = np.arange(0, 20, 2)
print(arr12)

[ 0  2  4  6  8 10 12 14 16 18]


In [22]:
arr13 = np.arange(0,1,0.2)
print(arr13)


[0.  0.2 0.4 0.6 0.8]


In [24]:
arr14= np.linspace(0,20,10,False) # 是否包含结束值
print(arr14)


[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [26]:
n1 = np.random.randint(1, 101)
print(n1)

23


In [27]:
arr15= np.random.randint(1,101,10)
print(arr15)


[50 31 38 82 33 30 46 78 80 70]


In [33]:
np.random.seed(1688)
n2= np.random.randint(1,101)
print(n2)


56


In [32]:
n3 = np.random.random() # 0-1之间随机数
print(n3)


0.756917773407644


In [34]:
n4 = np.random.random()*100 + 1
n4

7.063153777628183

In [ ]:
n5 = np.random.normal()

In [5]:
import numpy as np

np.random.seed(0)
p = np.array([0.1, 0.0, 0.7, 0.2])
for i in range(10):
    index = np.random.choice([1, 2, 3, 4], p=p.ravel())
    print(index)


3
3
3
3
3
3
3
4
4
3
