In [5]:
import numpy as np

In [6]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
arr2 = np.arange(15).reshape((3,5))
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

2
(3, 5)
15


In [11]:
print(arr1[0])

0


In [12]:
arr1[-1]

9

In [13]:
arr1[5:]

array([5, 6, 7, 8, 9])

In [14]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [15]:
arr2[0]

array([0, 1, 2, 3, 4])

In [16]:
arr2[0][0]

0

In [18]:
arr3 = arr2[:2,::2]
arr3

array([[0, 2, 4],
       [5, 7, 9]])

In [19]:
arr3[0,1] = 888

In [20]:
print(arr3)
print(arr2)

[[  0 888   4]
 [  5   7   9]]
[[  0   1 888   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [22]:
arr4 = arr2[:2, ::2].copy()
arr4[0,1] = 999
print(arr4)
print(arr2)

[[  0 999   4]
 [  5   7   9]]
[[  0   1 888   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]
